### ISSUE TITLE
I cannot understand how to use it,can you provide an example

### ISSUE THREAD

**Issue by 54lianxi** [vincekruger/flutter_whatsapp_stickers#4]

**Comment by 54lianxi** [comment]
I want to know which directory I should put the json file in and how to name the file ,webp image and tray icon where to put

**Comment by 54lianxi** [comment]
@vincekruger

**Comment by ahkohd** [comment]
> I want to know which directory I should put the JSON file in and how to name the file, WEBP image and tray icon where to put

1. At the root of your flutter project. Create a folder named `sticker_packs`
2. Edit your `pubspec.yaml` and add the folder you created earlier at the asset section
```yaml
assets:
    - sticker_packs/
```
3. In your `sticker_packs` folder, add the  `sticker_packs.json` and write the appropriate content. Sample content goes like this:
```json
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "Cuppy",
      "publisher": "Example Sticker Pack",
      "tray_image_file": "tray_Cuppy.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "01_Cuppy_smile.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "02_Cuppy_lol.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "03_Cuppy_rofl.webp",
          "emojis": ["😆","😂"]
        }
      ]
    }
  ]
}
```
   

**PS:** You should take a look at the sample project @vincekruger added to the source code
https://github.com/vincekruger/flutter_whatsapp_stickers/tree/master/example

**Comment by 54lianxi** [comment]
@ahkohd @vincekruger
 
I need to add emoticons dynamically, so JSON files and pack packages should be generated dynamically. It is not allowed to write them in the asset file

**Comment by ahkohd** [comment]
Once you have generated your emoticons dynamically all you need to do is the write a dart code that:
1. Move emoticons to your `identifier` folder in the  `sticker_packs` folder.
2. Dynamically create sticker_packs.json, place it in the `sticker_packs` folder.
3. Write the dynamic content into `sticker_packs.json` following the outlined schema. 

```
| - sticker_packs
    | - sticker_packs.json
    | - indentifier_folder_name
        | - sticker1.webp
        | - sticker2.webp
        | - sticker3.webp
```
With this library, I built an app that dynamically generates stickers,  https://play.google.com/store/apps/details?id=com.verge.sticker_cat, so yes you can.

PS: You should look at #1 The issue is also related to exporting a dynamically generated sticker pack.
