### ISSUE TITLE
Serious plugin fix

### ISSUE THREAD

**Issue by Ola4606** [vincekruger/flutter_whatsapp_stickers#8]
Ohh am sorry for the trouble sir. But this is my problem sir.. I really love your plugin am a fan.. I just don't know how to use it in a real life situation.. So am getting the stickers I want to use from my firebase and I want to upload unto my whatsapp like you have done.. But with your plugin you are using only images in the assets folder.. (which is not what I want to do cause I am downloading them). And since am doing that. The sticker.json file also needs to be changing each time a new sticker is uploaded or new sticker pack is created. I also think it would be nice to be able to check the number of stickers in each pack so that when the limit of 30 is reach a new pack can be made and a new json file also(I believe that is what the application "Sticker Maker" does ) .. Thank you sir.. Really hope you can help me solve this issue..

**Comment by vincekruger** [comment]
@Ola4606 Dude, I have a full-time job too.  There has been no update from Whatsapp regarding animated stickers (which is off-topic) but that is when I'm cycling back to this project again.

To answer your question... please read the documentation because dynamic sticker management is possible.

If you need my dedicated help, I will have to charge you for this.
